services:
  # Frontend application service (React/Vue/Angular)
  client:
    build:
      context: ./client
      dockerfile: Dockerfile

    container_name: client

    # Port mapping - host:container
    ports:
      - "5173:5173" # Vite default port

    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://localhost:5000 # For Vite

    volumes:
      - ./client:/app
      - /app/node_modules

    restart: unless-stopped

    # Frontend depends on backend API
    depends_on:
      - server

    # Network to communicate with backend
    networks:
      - app-network

  # Backend Node.js API service
  server:
    build:
      context: ./server
      dockerfile: Dockerfile

    container_name: server

    # Port mapping - host:container
    ports:
      - "5000:5000"

    # Environment variables
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb+srv://teosmile07:hp2wPbF0tUyNoicg@gatherly-mern-app.du8os6v.mongodb.net/?retryWrites=true&w=majority&
      - CLIENT_URL=http://localhost:5173

    # Mount local directory to container for development
    volumes:
      - ./server:/app
      - /app/node_modules

    # Restart policy
    restart: unless-stopped

    # Wait for MongoDB to be ready
    # depends_on:
    #   - mongodb

    networks:
      - app-network

# Networks for container communication
networks:
  app-network:
    driver: bridge
